export { HomeComponent } from './home-theme/home/home.component';
export { ProductsComponent } from './demo-theme/content-demo-theme/products/products.component';
export { ProductComponent } from './demo-theme/content-demo-theme/product/product.component';
export { HomeDemoThemeComponent } from './demo-theme/home-demo-theme/home-demo-theme.component';
export { DemoLoginComponent } from './demo-theme/content-demo-theme/demo-login/demo-login.component';
export { CreateProductComponent } from './demo-theme/content-demo-theme/create-product/create-product.component';
export { EditProductComponent} from './demo-theme/content-demo-theme/edit-product/edit-product.component';
export { UserProfileComponent } from './demo-theme/content-demo-theme/user-profile/user-profile.component';
export { SalesOrdersComponent} from './demo-theme/content-demo-theme/sales-orders/sales-orders.component';
export { SalesOrderComponent} from './demo-theme/content-demo-theme/sales-order/sales-order.component';
export { ShoppingcartComponent } from './demo-theme/content-demo-theme/shopping-cart/shoppingcart.component';
export { CheckoutComponent } from './demo-theme/content-demo-theme/checkout/checkout.component';
export { AdminProductsComponent }  from './demo-theme/content-demo-theme/admin-products/admin-products.component';
export { AboutComponent } from './demo-theme/content-demo-theme/about/about.component';
export { DashboardSalesComponent } from './demo-theme/dashboard-sales/dashboard-sales.component';
export { ReportsComponent }  from './demo-theme/reports/reports.component';